# Site settings
title: BATTLE
description: Deep learning for enhanced phage therapy
# Use blank baseurl and local server when testing locally
# baseurl: "" 
# url: "http://localhost:4000"
baseurl: "/TeamBattle-Site"
url: "https://phagebattle.com/"

email: teambattle.gems@gmail.com

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  team:
    output: false

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"